//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 Monitor.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_GraphViewTYPE               130
#define IDR_MeddleViewTYPE              131
#define ID_WINDOW_MANAGER               132
#define IDR_FloatingProfitViewTYPE      133
#define ID_VIEW_OUTPUTWND               149
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDS_OUTPUT_WND                  157
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDR_OUTPUT_POPUP                182
#define ID_VIEW_NAVIGATION              185
#define IDB_NAVIGATION_LARGE            186
#define IDB_NAVIGATION_LARGE_HC         187
#define IDB_PAGES                       188
#define IDB_PAGES_HC                    189
#define IDB_PAGES_SMALL                 190
#define IDB_PAGES_SMALL_HC              191
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_MYCALENDARS                 250
#define IDS_CALENDAR                    251
#define IDS_SHORTCUTS                   252
#define IDS_FOLDERS                     253
#define IDS_OUTLOOKBAR                  258
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDR_MENU_R_CLICK                310
#define IDD_DIALOG_ADD_SOURCE           311
#define IDD_DIALOG_DEPLOY_STRATEGY      315
#define IDD_DIALOG_STRATEGY_MEDDLE      318
#define IDD_DIALOG_MEDDLE               320
#define IDD_DIALOG_UPDATE_STRATEGY_BIN  322
#define IDD_DIALOG_SET_SHARE_VALUE      324
#define IDD_DIALOG_UPDATE_ORDER_TICKET  326
#define IDC_COMBO_SOURCE_TYPE           1000
#define IDC_MFCPROPERTYGRID_SOURCE_PROP 1001
#define IDC_COMBO_DEPLOY_STRATEGY_STRATEGY_BIN 1003
#define IDC_EDIT_DEPLOY_STRATEGY_ARCHIVE_PATH 1004
#define IDC_MFCPROPERTYGRID_DEPLOY_STRATEGY_DATAID 1005
#define IDC_MFCPROPERTYGRID2            1006
#define IDC_MFCPROPERTYGRID_DEPLOY_STRATEGY_PARAM 1006
#define IDC_BUTTON_DEPLOY_STRATEGY_ADD_DATAID 1007
#define IDC_COMBO_DEPLOY_STRATEGY_ARCHIVE_PATH 1008
#define IDC_EDIT_MEDDLE_INPUT           1009
#define IDC_BUTTON_MEDDLE_SUBMIT        1010
#define IDC_LIST_MEDDLE_RESPONSE        1011
#define IDC_BUTTON_MEDDLE_FETCH         1012
#define IDC_EDIT_DEPLOY_STRATEGY_STRATEGY_COMMENT 1013
#define IDC_EDIT_MEDDLE_COMMAND         1014
#define IDC_BUTTON_SEND_MEDDLE          1015
#define IDC_BUTTON_GET_MEDDLE_RESPONSE  1017
#define IDC_COMBO1                      1018
#define IDC_EDIT_INDEX                  1019
#define IDC_EDIT_NEW_VALUE              1020
#define IDC_EDIT_DEPLOY_STRATEGY_MAX_TICKETS_PER_DAY 1021
#define IDC_EDIT_STRATEGY_MAX_TICKET    1022
#define IDC_EDIT_STRATEGY_REMAIN_TICKET 1023
#define IDC_STATIC_STRATEGY_LABEL       1024
#define IDC_STATIC_COMMAND              1025
#define IDC_CHECK1                      1027
#define IDC_CHECK_IS_BATCH_DEPLOY       1027
#define IDC_EDIT1                       1028
#define IDC_BUTTON_SELECT_BATCH_CSV_FILE 1029
#define IDC_LIST1                       1031
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_SOURCEBLACKRCLICK_ADD_MD_SOURCE 32772
#define ID_SOURCEITEMRCLICK_DEL_MD_SOURCE 32774
#define ID_SOURCEBLACKRCLICK_ADD_TD_SOURCE 32780
#define ID_SOURCEITEMRCLICK_DEL_TD_SOURCE 32781
#define ID_STRATEGYBLACK_32782          32782
#define ID_STRATEGYITEM_32783           32783
#define ID_STRATEGYBLACK_DEPLOY_NEW_STRATEGY 32784
#define ID_STRATEGYITEM_CANCEL_STRATEGY 32785
#define ID_PARAMCONFIG_PASTE_PARAM      32789
#define ID_PARAMCONFIG_CLEAR_MARAM      32791
#define ID_STRATEGYITEM_32792           32792
#define ID_STRATEGYITEM_STRATEGY_SUPERVISORY 32793
#define ID_STRATEGYBLACK_32795          32795
#define ID_OUTLOOKBAR_32797             32797
#define ID_OUTLOOKBAR_LOAD_CMD_FROM_JSON 32798
#define ID_WINDOW_LAYOUT_FOCUS          32799
#define ID_WINDOW_LAYOUT_MEAN           32800
#define ID_WINDOW_LAYOUT_HORIZ_FIRST    32801
#define ID_STRATEGYITEM_32802           32802
#define ID_STRATEGYITEM_STRATEGY_SAVE_CONFIG_JSON 32803
#define ID_STRATEGYITEM_32804           32804
#define ID_STRATEGYITEM_STRATEGY_UPDATE_BIN 32805
#define ID_WINDOW_LAYOUT_FREEZN         32807
#define ID_STRATEGYITEM_32808           32808
#define ID_STRATEGYITEM_CANCEL_STRATEGY_AND_SAVE 32809
#define ID_BUTTON_RESET_PROBE_GRAPH     32810
#define ID_BUTTON3                      32811
#define ID_BUTTON_RESET_ALL_PROBE_GRAPH 32811
#define ID_BUTTON2                      32812
#define ID_BUTTON_SHOW_HIDE_CUSTOM_BUTTON 32812
#define ID_SETSHAREDVALUE_32813         32813
#define ID_SETSHAREDVALUE               32814
#define ID_STRATEGYBLACK_32815          32815
#define ID_STRATEGYITEM_32817           32817
#define ID_STRATEGYITEM_STRATEGY_UPDATE_ORDER_TICKET 32818

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        328
#define _APS_NEXT_COMMAND_VALUE         32819
#define _APS_NEXT_CONTROL_VALUE         1032
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
